name: Build Code Documentation

on:
  push:
    branches:
      - main
    paths:
      - "**.bs"
      - "**.brs"

jobs:
  notify-docs-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Documentation Workflow
        uses: peter-evans/repository-dispatch@28959ce8df70de7be546dd1250a005dd32156697 # v4.0.1
        with:
          token: ${{ secrets.JELLYROCK_BOT_TOKEN }}
          repository: jellyrock/api-docs
          event-type: code-update
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
